#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Config-General
Version  : 2.63
Release  : 25
URL      : https://cpan.metacpan.org/authors/id/T/TL/TLINDEN/Config-General-2.63.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/T/TL/TLINDEN/Config-General-2.63.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libc/libconfig-general-perl/libconfig-general-perl_2.63-1.debian.tar.xz
Summary  : unknown
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Config-General-license
Requires: perl-Config-General-man

%description
NAME
Config::General - Generic Config Module
SYNOPSIS
use Config::General;
$conf = new Config::General(-ConfigFile => "myconfig.rc");
my %config = $conf->getall;

%package license
Summary: license components for the perl-Config-General package.
Group: Default

%description license
license components for the perl-Config-General package.


%package man
Summary: man components for the perl-Config-General package.
Group: Default

%description man
man components for the perl-Config-General package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Config-General-2.63
mkdir -p %{_topdir}/BUILD/Config-General-2.63/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Config-General-2.63/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Config-General
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-Config-General/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Config/General.pm
/usr/lib/perl5/site_perl/5.26.1/Config/General/Extended.pm
/usr/lib/perl5/site_perl/5.26.1/Config/General/Interpolated.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Config-General/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Config::General.3
/usr/share/man/man3/Config::General::Extended.3
/usr/share/man/man3/Config::General::Interpolated.3
