#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Config-General
Version  : 2.58
Release  : 9
URL      : http://search.cpan.org/CPAN/authors/id/T/TL/TLINDEN/Config-General-2.58.tar.gz
Source0  : http://search.cpan.org/CPAN/authors/id/T/TL/TLINDEN/Config-General-2.58.tar.gz
Summary  : ~
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Config-General-doc

%description
NAME
Config::General - Generic Config Module
SYNOPSIS
use Config::General;
$conf = new Config::General(-ConfigFile => "myconfig.rc");
my %config = $conf->getall;

%package doc
Summary: doc components for the perl-Config-General package.
Group: Documentation

%description doc
doc components for the perl-Config-General package.


%prep
%setup -q -n Config-General-2.58

%build
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make V=1  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=intel.com,localhost
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.22.0/Config/General.pm
/usr/lib/perl5/site_perl/5.22.0/Config/General/Extended.pm
/usr/lib/perl5/site_perl/5.22.0/Config/General/Interpolated.pm

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*
